spring.application.name=orders
spring.flyway.locations=db/migration
spring.datasource.url=jdbc:postgresql://localhost:5432/orders
spring.datasource.username=postgres
spring.datasource.password=postgres

