CREATE TABLE ORDERS (
  ID INT PRIMARY KEY,
  ITEM_ID INT NOT NULL,
  CUSTOMER_ID INT NOT NULL,
  DATE DATE NOT NULL,
  TOTAL DECIMAL NOT NULL,
  SHIPPING_ADDRESS VARCHAR(255) NOT NULL,
  STATUS VARCHAR(255) NOT NULL
);
